# Generated by Django 3.2.12 on 2022-07-14 09:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Сожержимое поста'),
        ),
    ]
